### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kipkurui** [BioinfoNet/OpenScienceKE#11]
**OpenScienceKE: Project Mission & Summary**

OpenScienceKE seeks to promote open, collaborative and reproducible Bioinformatics Research in Nairobi, Kenya. 

**Milestones reached***
- [x] Seminars:  Held 4 seminars at local Universities in May
- [x] [Workshops](https://bioinfonet.github.io/OpenScienceKE/): Held a two-day workshop early August (9-10th)
- [x] [Hackathons](https://github.com/BioinfoNet/OpenScienceKEHackathon): Held a two-day hackathon late August (30-31)

**Target Milestones**
1. Complete the hackathon projects: After the hackathon, where we worked on three projects, there is a need to follow-up with the participants to complete the projects. This is an area where collaborations and contributions are welcome, and encouraged in the following areas:
    - [x] [Data mining:](https://github.com/BioinfoNet/Data-mining) We are mining abstracts of all papers published in Kenya for collaboration trends, open access trends, and whether the authors make the data and code openly accessible.
    - [x] [Status of Open Science in Kenya:](https://github.com/BioinfoNet/Status-of-OpenScienceKE-LiteratureSearch) We are interested in establishing where we are in adopting open science in Kenya: Available infrastructure, Policies, training etc. 
    - [x] [Publishing Open Access:](https://github.com/BioinfoNet/LowCostOpenAccess) We are creating a resource for students and early career scientists who are interested in publishing open access but may not have funding. The resource will contain a list of journals that offer subsidies or waivers to papers from Lower and Middle-Income Countries, including Kenya. 
2. Collaborative Paper
    - [x] We are interested in publishing the hackathon output in an open access journal. We are using markdown for collaborative writing. may need help with continuous integration. Currently, we can convert the paper to Latex and Pdf in Travis, but we cannot commit the final pdf to repo
    - [x] Should get the first draft complete by end of October
3. Meetups:
    - [x] We are also planning to host the first meet up in November

**Comment by ousodaniel** [comment]
Well noted @kipkurui, thanks
